USE QLVT_DATHANG
GO
CREATE PROC SP_GRANT_SP_PERMISSION
AS
BEGIN
	GRANT EXECUTE ON SP_DANGNHAP TO CONGTY
	GRANT CONTROL ON SP_DANGNHAP TO CONGTY
	GRANT EXECUTE ON SP_DDH_CHUA_NHAP TO CONGTY
	GRANT CONTROL ON SP_DDH_CHUA_NHAP TO CONGTY
	GRANT EXECUTE ON SP_DSNV TO CONGTY
	GRANT CONTROL ON SP_DSNV TO CONGTY
	GRANT EXECUTE ON SP_List_LOGIN TO CONGTY
	GRANT CONTROL ON SP_List_LOGIN TO CONGTY
	GRANT EXECUTE ON SP_SLVT TO CONGTY
	GRANT CONTROL ON SP_SLVT TO CONGTY
	GRANT EXECUTE ON SP_TAOLOGIN TO CONGTY
	GRANT CONTROL ON SP_TAOLOGIN TO CONGTY
	GRANT EXECUTE ON SP_TKPN TO CONGTY
	GRANT CONTROL ON SP_TKPN TO CONGTY
	GRANT EXECUTE ON SP_TKPX TO CONGTY
	GRANT CONTROL ON SP_TKPX TO CONGTY
END