CREATE PROC [dbo].[SP_TKPX] @start NVARCHAR(20),@end NVARCHAR(20),@ct int
AS
BEGIN
	IF 1=0 BEGIN
		SET FMTONLY OFF
	END
	SELECT * INTO #px  FROM dbo.PhieuXuat WHERE NGAY BETWEEN CONVERT(DATETIME,@start,103) AND CONVERT(DATETIME,@end,103)

	SELECT MAVT,CAST(Month(#px.NGAY) as varchar) + '-' + cast(YEAR(#px.NGAY) as varchar) AS NGAY,SUM(SOLUONG) AS TONGSL,SUM(DONGIA) AS TONGGIA
	INTO #temp
	FROM #px JOIN dbo.CTPX ON dbo.CTPX.MAPX =#px.MAPX  
	GROUP BY MAVT,CAST(Month(#px.NGAY) as varchar) + '-' + cast(YEAR(#px.NGAY) as varchar) 

	SELECT NGAY,TENVT,TONGSL,TONGGIA INTO #kq FROM #temp JOIN dbo.Vattu ON Vattu.MAVT = #temp.MAVT

	IF(@ct=0)
	BEGIN
		SELECT * FROM #kq
	END
	ELSE
	BEGIN
	
	SELECT * INTO #px1  FROM LINK_QLVT.QLVT_DATHANG.dbo.PhieuXuat WHERE NGAY BETWEEN CONVERT(DATETIME,@start,103) AND CONVERT(DATETIME,@end,103)
	SELECT MAVT,CAST(Month(#px1.NGAY) as varchar) + '-' + cast(YEAR(#px1.NGAY) as varchar) AS NGAY,SUM(SOLUONG) AS TONGSL,SUM(DONGIA) AS TONGGIA
	INTO #temp1
	FROM #px1 JOIN LINK_QLVT.QLVT_DATHANG.dbo.CTPX AS ct on ct.MAPX=#px1.MAPX
	GROUP BY MAVT,CAST(Month(#px1.NGAY) as varchar) + '-' + cast(YEAR(#px1.NGAY) as varchar) 

	SELECT NGAY,TENVT,TONGSL,TONGGIA INTO #kq1 FROM #temp1 JOIN dbo.Vattu ON Vattu.MAVT = #temp1.MAVT

	INSERT INTO #kq1 SELECT * FROM #kq
	SELECT NGAY,TENVT,SUM(TONGSL) AS TONGSL,SUM(TONGGIA) as TONGGIA FROM #kq1 GROUP BY TENVT,NGAY
	END
    
END
