CREATE TRIGGER [dbo].[TG_UPDATE_NhapHang]
ON [dbo].[CTPN]
FOR UPDATE
AS
BEGIN
	DECLARE @HieuSo INT, @InsertedSOLUONG INT, @InsertedMAVT nvarchar(4), @MasoDDH nchar(8), @SOLUONG_NHAP INT;
	SET @InsertedSOLUONG = (SELECT SOLUONG FROM inserted);
	SET @InsertedMAVT = (SELECT MAVT FROM inserted);
	SET @MasoDDH = (SELECT MasoDDH FROM PhieuNhap where MAPN = (SELECT MAPN FROM inserted))
	SET @SOLUONG_NHAP = (SELECT SOLUONG FROM CTDDH WHERE MAVT = @InsertedMAVT AND MasoDDH = @MasoDDH);
	if(@InsertedSOLUONG > @SOLUONG_NHAP)
	begin
		RAISERROR(N'QUA SO LUONG at column ''SOLUONG''.',16,1);
		ROLLBACK;

	end
END